In [ ]:
import numpy as np


In [ ]:
simple_list=[24,53,65]
np.array(simple_list)

array([24, 53, 65])

In [ ]:
arr_1=[[3247,32,45],[35,456,43],[345,46,28]]

In [ ]:
np.array(arr_1)

array([[3247,   32,   45],
       [  35,  456,   43],
       [ 345,   46,   28]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.arrange(3,4)

AttributeError: ignored

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.ones(2,5)

TypeError: ignored

In [ ]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [15]:
np.linspace(0,20,dtype=int)

array([ 0,  0,  0,  1,  1,  2,  2,  2,  3,  3,  4,  4,  4,  5,  5,  6,  6,
        6,  7,  7,  8,  8,  8,  9,  9, 10, 10, 11, 11, 11, 12, 12, 13, 13,
       13, 14, 14, 15, 15, 15, 16, 16, 17, 17, 17, 18, 18, 19, 19, 20])

In [16]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [17]:
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [18]:
np.eye(3,3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.eye(3,3,k=4)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.random.rand(4,5)

array([[0.14219184, 0.53496288, 0.16553072, 0.80176898, 0.08135674],
       [0.56202427, 0.70121432, 0.86982578, 0.92199594, 0.00388668],
       [0.45485135, 0.84337386, 0.95616029, 0.34452548, 0.94201964],
       [0.46618598, 0.13304775, 0.58734483, 0.26036704, 0.0735329 ]])

In [21]:
np.random.randn(4,5)

array([[-0.82172336, -0.36787556,  1.50612391, -1.28978457,  1.93945865],
       [-0.0062234 ,  0.87097845,  1.23336315, -0.84056166,  0.22718704],
       [ 0.24965055, -0.77484044, -1.19775555, -0.49628422, -0.15667424],
       [-0.60695212,  0.10037171,  0.7697746 , -0.55427396,  0.13867879]])

In [22]:
np.random.randn(4,5,dtype=int)

TypeError: ignored

In [27]:
np.random.randint(22,24)

23

In [28]:
np.random.randint(0,1,100)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.random.randint(0,2,100)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1])

In [30]:
sample_data=np.random.randint(0,10,5)
sample_data

array([2, 5, 8, 7, 3])

In [31]:
sample_data.min()

2

In [32]:
sample_data.max()

8

In [33]:
sample_data.argmin() ##gives the position of the minimum value

0

In [34]:
sample_data.argmax() ##gives the position of the maximum value

2

In [35]:
np.random.randn(4,5)

array([[ 0.78592779,  0.58848225,  0.34915949, -2.27192416, -1.5597765 ],
       [ 0.19116212, -0.81671222,  0.85272537,  1.28086076, -1.31763426],
       [-2.03924966, -1.27110753, -0.11373331,  0.5663077 ,  0.63619417],
       [ 2.35451909,  2.19612858, -0.28646323, -0.93075632,  1.25650766]])

In [36]:
a=np.random.randn(4,5)
a

array([[ 0.38798578, -1.16170184, -0.09698138, -0.36602472, -0.12661292],
       [ 1.52249315, -1.75231604, -0.50536859,  0.79525998,  0.81805502],
       [-1.00426839, -0.6334198 ,  0.04568902,  0.78942593, -0.86823556],
       [-0.69590255, -1.84632453,  1.5389732 ,  2.35167173, -0.43624117]])

In [37]:
a.T

array([[ 0.38798578,  1.52249315, -1.00426839, -0.69590255],
       [-1.16170184, -1.75231604, -0.6334198 , -1.84632453],
       [-0.09698138, -0.50536859,  0.04568902,  1.5389732 ],
       [-0.36602472,  0.79525998,  0.78942593,  2.35167173],
       [-0.12661292,  0.81805502, -0.86823556, -0.43624117]])

In [38]:
a.dtype()

TypeError: ignored

In [39]:
a.dtype

dtype('float64')

In [40]:
np.random.randn(2,3,dtype=int)

TypeError: ignored

In [41]:
np.random.randn((2,3),dtype=int)

TypeError: ignored

In [42]:
c=np.random.randint(20,45,6)
c

array([24, 30, 28, 22, 23, 43])

In [43]:
c=c.r.reshape(2,3)

AttributeError: ignored

In [44]:
c=c.reshape(2,3)

In [45]:
c

array([[24, 30, 28],
       [22, 23, 43]])

In [46]:
c.max()

43

In [47]:
c.argmax()

5

In [48]:
d=c.reshape(3,2)

In [49]:
d.max()

43

In [50]:
d.argmax()

5

In [51]:
d[1:]

array([[28, 22],
       [23, 43]])

In [52]:
d[1,0]

28

In [53]:
d[1,2]

IndexError: ignored

In [54]:
a=np.random.randn(2,3)
b=np.random.randint(2,3)

In [55]:
c=a+b
c

array([[2.97154856, 1.72199111, 1.79230952],
       [1.41949184, 1.68558783, 3.71916844]])

In [56]:
np.exp(c)

array([[19.52212737,  5.59565896,  6.00330119],
       [ 4.13501866,  5.39562168, 41.23009459]])

In [57]:
np.log(c)

array([[1.08908322, 0.54348124, 0.58350502],
       [0.35029895, 0.52211436, 1.31350011]])

In [58]:
np.max(c)

3.719168440927252

In [59]:
np.argmax(c)

5

In [60]:
np.min(c)

1.419491840579632

In [61]:
np.argmin(c)

3

In [62]:
np.square(c)

array([[ 8.83010084,  2.96525339,  3.2123734 ],
       [ 2.01495709,  2.84120632, 13.83221389]])

In [63]:
np.std(c)

0.8336322727305056

In [64]:
np.mean(c)

2.218349548837704

In [65]:
np.var(c)

0.6949427661378279

In [66]:
f=np.var(c)
np.round(f,decimals=4)

0.6949

In [67]:
Names=np.array['Sanyam','rahul','pratham','mishra']
np.unique(Names)

TypeError: ignored

In [69]:
names=np.array(['sanyam','pratham','pratham','mishra'])
np.unique(names)

array(['mishra', 'pratham', 'sanyam'], dtype='<U7')